### ISSUE TITLE
env.reset(), giving error

### ISSUE THREAD

**Issue by Chetanbuye12** [Inoryy/Deep-RL-Bootcamp-Labs#1]
WARN: Could not seed environment <FrozenLakeEnv instance>

NotImplementedError                       Traceback (most recent call last)
<ipython-input-8-94a2f043eda8> in <module>()
      8 env.seed(0); from gym.spaces import prng; prng.seed(10)
      9 # Generate the episode
---> 10 env.reset()
     11 for t in range(100):
     12     env.render()

C:\Users\Admin\Anaconda3\lib\site-packages\gym\core.py in reset(self)
     69             space.
     70         """
---> 71         raise NotImplementedError
     72 
     73     def render(self, mode='human'):

NotImplementedError:

**Comment by inoryy** [comment]
Hello, the code should work as it is. Maybe you didn't install some dependencies? Have you followed the pre-lab guide: https://github.com/inoryy/Deep-RL-Bootcamp-Labs/blob/master/prelab/prelab.pdf
